name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/WFCD/warframe-drop-data.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
